name: Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand(\"ping\").ok'" 
          --health-interval=10s 
          --health-timeout=10s 
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=ce25a89e-6835-4946-9f03-cd154803bea5 --base-path http://localhost:3000/products --cloud

      - name: Print MongoDB logs if failed
        if: failure()
        run: |
          docker ps -a
          docker logs $(docker ps -aqf "ancestor=mongo:4.4")
